/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import javax.swing.JOptionPane;
import Clases.Conexion;
import Clases.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Nataly
 */
public class Facultades extends javax.swing.JInternalFrame {
Conexion con;
Facultades facultad;
    /**
     * Creates new form Facultades
     */
    public Facultades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_Nombre_Facultad = new javax.swing.JLabel();
        lbl_Estado_Facultad = new javax.swing.JLabel();
        btn_Guardar_Facultad = new javax.swing.JButton();
        btn_Eliminar_Facultad = new javax.swing.JButton();
        btn_Actualizar_Facultad = new javax.swing.JButton();
        Txt_Nombre_Facultad = new javax.swing.JTextField();
        chkb_estado_facultad = new javax.swing.JCheckBox();
        btn_Nuevo_Facultad = new javax.swing.JButton();
        cbx_facultades = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_Facultad = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        lbl_Nombre_Facultad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Nombre_Facultad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre_Facultad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Nombre_Facultad.setText("Nombre Facultad:");

        lbl_Estado_Facultad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Estado_Facultad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Estado_Facultad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Estado_Facultad.setText("Estado Facultad:");

        btn_Guardar_Facultad.setText("Guardar");
        btn_Guardar_Facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Guardar_FacultadActionPerformed(evt);
            }
        });

        btn_Eliminar_Facultad.setText("Eliminar");
        btn_Eliminar_Facultad.setEnabled(false);
        btn_Eliminar_Facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_FacultadActionPerformed(evt);
            }
        });

        btn_Actualizar_Facultad.setEnabled(false);
        btn_Actualizar_Facultad.setLabel("Actualizar");
        btn_Actualizar_Facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Actualizar_FacultadActionPerformed(evt);
            }
        });

        btn_Nuevo_Facultad.setText("Nuevo");
        btn_Nuevo_Facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Nuevo_FacultadActionPerformed(evt);
            }
        });

        cbx_facultades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_facultadesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cbx_facultades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Eliminar_Facultad))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Nuevo_Facultad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Guardar_Facultad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Actualizar_Facultad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_Nombre_Facultad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Estado_Facultad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkb_estado_facultad)
                            .addComponent(Txt_Nombre_Facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Eliminar_Facultad)
                    .addComponent(cbx_facultades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Nombre_Facultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nombre_Facultad))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkb_estado_facultad)
                    .addComponent(lbl_Estado_Facultad))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar_Facultad)
                    .addComponent(btn_Actualizar_Facultad)
                    .addComponent(btn_Nuevo_Facultad))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lbl_Facultad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Facultad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Facultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Facultad.setText("Facultad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lbl_Facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_Facultad)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Guardar_FacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Guardar_FacultadActionPerformed
      /*  Facultades facultad = new Facultades();
        try {
  //          UnidadAcademica unidad = (UnidadAcademica) cbx_Cod_Unid_Academica.getSelectedItem();
            facultad.setNombre_Facultad(this.Txt_Nombre_Facultad.getText());
            facultad.setEstado_Facultad(this.chkb_estado_facultad.isSelected());
           // facultad.setCod_Unid_Academica(unidad.getCod_Unid_Academica());
        } catch (Exception ex) {
            Logger.getLogger(FacultadForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        Integer id = facultad.guardar(con); //guarda el registro y retorna el id generado

        if (id != null) {
            facultad.setCod_Facultad(id.intValue());
            cbx_facultades.addItem(facultad);
            if (facultad.isEstado_Facultad()) {
                cbx_Cod_Facultad.addItem(facultad);
            }

          //  this.btn_nuevo_unidadActionPerformed(null);
            JOptionPane.showMessageDialog(null, "El Registro se Guardo con Exito");
        } else {
            JOptionPane.showMessageDialog(null, "Error , Fallo al Guardar el Registro");
        }*/
    }//GEN-LAST:event_btn_Guardar_FacultadActionPerformed

    private void btn_Eliminar_FacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_FacultadActionPerformed
    /*    Facultades facultad = (Facultades) cbx_facultades.getSelectedItem();
        if (facultad != null && facultad.getNombre_Facultad() != null) {
            int result = JOptionPane.showConfirmDialog(this, "Desea Eliminar el Registro", "Salir", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_NO_OPTION) {
                if (facultad.eliminar(con)) {
                    JOptionPane.showMessageDialog(null, "El Registro se Elimino con Exito");
                    this.btn_Nuevo_FacultadActionPerformed(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Error , Fallo al Eliminar el Registro");
                }
            }
        }
        this.obtenerFacultades();
        */
    }//GEN-LAST:event_btn_Eliminar_FacultadActionPerformed

    private void btn_Actualizar_FacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Actualizar_FacultadActionPerformed
      /*  Facultades facultad = (Facultades) cbx_facultades.getSelectedItem();
//        UnidadAcademica unidad = (UnidadAcademica) cbx_Cod_Unid_Academica.getSelectedItem();
        if (facultad != null && facultad.getNombre_Facultad() != null) {
            facultad.setNombre_Facultad(this.Txt_Nombre_Facultad.getText());
            facultad.setEstado_Facultad(this.chkb_estado_facultad.isSelected());
            facultad.setCod_Unid_Academica(unidad.getCod_Unid_Academica());
            if (facultad.actualizar(con)) {
                JOptionPane.showMessageDialog(null, "El Registro se actualizo con Exito");
                this.btn_Nuevo_FacultadActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(null, "Error , Fallo al actualizar el Registro");
            }
        }
        this.obtenerFacultades();
              */
    }//GEN-LAST:event_btn_Actualizar_FacultadActionPerformed

    private void btn_Nuevo_FacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Nuevo_FacultadActionPerformed
    /*    this.Txt_Nombre_Facultad.setText("");
        this.chkb_estado_facultad.setSelected(false);
        this.cbx_Cod_Unid_Academica.setSelectedIndex(0);
        this.cbx_facultades.setSelectedIndex(0);
            */
    }//GEN-LAST:event_btn_Nuevo_FacultadActionPerformed

    private void cbx_facultadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_facultadesItemStateChanged
   /*     if (evt.getStateChange() == ItemEvent.SELECTED) {
            Facultades item = (Facultades) evt.getItem();
            if (item.getNombre_Facultad() != null) {
                controlesFacultades(false);
                this.Txt_Nombre_Facultad.setText(item.getNombre_Facultad());
                this.chkb_estado_facultad.setSelected(item.isEstado_Facultad());
         //       this.cbx_Cod_Unid_Academica.setSelectedItem(new UnidadAcademica(item.getCod_Unid_Academica()));
            } else {
                controlesFacultades(true);
            }
        }
           */
    }//GEN-LAST:event_cbx_facultadesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_Nombre_Facultad;
    private javax.swing.JButton btn_Actualizar_Facultad;
    private javax.swing.JButton btn_Eliminar_Facultad;
    private javax.swing.JButton btn_Guardar_Facultad;
    private javax.swing.JButton btn_Nuevo_Facultad;
    private javax.swing.JComboBox cbx_facultades;
    private javax.swing.JCheckBox chkb_estado_facultad;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Estado_Facultad;
    private javax.swing.JLabel lbl_Facultad;
    private javax.swing.JLabel lbl_Nombre_Facultad;
    // End of variables declaration//GEN-END:variables
}
