/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Conexion;
import Clases.tablas.Bitacoras;
import Clases.tablas.Usuarios;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;

/**
 *
 * @author Erika
 */
public class Main extends javax.swing.JFrame {

    private Usuarios usuario;
    private Conexion con;

    /**
     * Creates new form Main
     *
     * @param nombreDeUsuario
     */
    public Main(String nombreDeUsuario) throws SQLException {
        initComponents();
        this.setExtendedState(Main.MAXIMIZED_BOTH);
        con = new Conexion();
        usuario = Usuarios.getUsuario(con, nombreDeUsuario);

        lbl_status.setText(usuario.getPersona().nombreCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jXStatusBar1 = new org.jdesktop.swingx.JXStatusBar();
        lbl_status = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFormulario = new javax.swing.JMenu();
        submenuF1 = new javax.swing.JMenuItem();
        submenuF2 = new javax.swing.JMenuItem();
        MenuMantenimientos = new javax.swing.JMenu();
        menuMttoPersonas = new javax.swing.JMenuItem();
        menuMttoMaterias = new javax.swing.JMenuItem();
        menuMttoUsuarios = new javax.swing.JMenuItem();
        MenuBitacora = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jXStatusBar1.setLayout(new java.awt.GridLayout(1, 0));
        jXStatusBar1.add(lbl_status);

        MenuFormulario.setText("Formularios");

        submenuF1.setText("Reserva de Parcial");
        submenuF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuF1ActionPerformed(evt);
            }
        });
        MenuFormulario.add(submenuF1);

        submenuF2.setText("Solicitar Recurso");
        submenuF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuF2ActionPerformed(evt);
            }
        });
        MenuFormulario.add(submenuF2);

        jMenuBar1.add(MenuFormulario);

        MenuMantenimientos.setText("Mantenimientos");

        menuMttoPersonas.setText("Personas");
        menuMttoPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMttoPersonasActionPerformed(evt);
            }
        });
        MenuMantenimientos.add(menuMttoPersonas);

        menuMttoMaterias.setText("Materias");
        menuMttoMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMttoMateriasActionPerformed(evt);
            }
        });
        MenuMantenimientos.add(menuMttoMaterias);

        menuMttoUsuarios.setText("Usuarios");
        menuMttoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMttoUsuariosActionPerformed(evt);
            }
        });
        MenuMantenimientos.add(menuMttoUsuarios);

        jMenuBar1.add(MenuMantenimientos);

        MenuBitacora.setText("Bitacora");
        jMenuBar1.add(MenuBitacora);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jXStatusBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXStatusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMttoPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMttoPersonasActionPerformed
        try {
            Personas personaForm = new Personas();
            jDesktopPane1.add(personaForm);
            personaForm.show();
            personaForm.setMaximizable(true);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuMttoPersonasActionPerformed

    private void menuMttoMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMttoMateriasActionPerformed
        try {
            Materias materiasForm = new Materias();
            jDesktopPane1.add(materiasForm);
            materiasForm.show();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuMttoMateriasActionPerformed

    private void menuMttoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMttoUsuariosActionPerformed
        try {
            RolesUsuariosForm rolesUsuariosForm = new RolesUsuariosForm();
            jDesktopPane1.add(rolesUsuariosForm);
            rolesUsuariosForm.show();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuMttoUsuariosActionPerformed

    private void submenuF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuF1ActionPerformed
        try {
            Reserva_Parcial reservas = new Reserva_Parcial();
            jDesktopPane1.add(reservas);
            reservas.show();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submenuF1ActionPerformed

    private void submenuF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuF2ActionPerformed
        try {
            Recursos_solicitados recursos = new Recursos_solicitados();
            jDesktopPane1.add(recursos);
            recursos.show();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submenuF2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBitacora;
    private javax.swing.JMenu MenuFormulario;
    private javax.swing.JMenu MenuMantenimientos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private org.jdesktop.swingx.JXStatusBar jXStatusBar1;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JMenuItem menuMttoMaterias;
    private javax.swing.JMenuItem menuMttoPersonas;
    private javax.swing.JMenuItem menuMttoUsuarios;
    private javax.swing.JMenuItem submenuF1;
    private javax.swing.JMenuItem submenuF2;
    // End of variables declaration//GEN-END:variables
}
