/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;
import Clases.Conexion;
import clases.tablas.*;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Nataly
 */
public class Materias extends javax.swing.JInternalFrame {

    /**
     * Creates new form Materias
     */
    public Materias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_Materia = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_NombreMateria = new javax.swing.JTextField();
        txt_Abreviatura_Materia = new javax.swing.JTextField();
        txt_UV = new javax.swing.JTextField();
        txt_CicloMateria = new javax.swing.JTextField();
        btn_GuardarMateria = new javax.swing.JButton();
        btn_Actualizar_Materias = new javax.swing.JButton();
        btn_EliminarMaterias = new javax.swing.JButton();
        cbx_Cod_Facultad = new javax.swing.JComboBox();
        chkb_estado_materia = new javax.swing.JCheckBox();
        cbx_materias = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        btn_Nuevo_Materia = new javax.swing.JButton();

        jpanel_Materia.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Formulario de Materias");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Código Facultad");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre de Materia");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Abreviatura Materia");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("U.V.");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ciclo de Materia");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estado de Materia");

        txt_UV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UVActionPerformed(evt);
            }
        });
        txt_UV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UVKeyTyped(evt);
            }
        });

        txt_CicloMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CicloMateriaKeyTyped(evt);
            }
        });

        btn_GuardarMateria.setText("Guardar");
        btn_GuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarMateriaActionPerformed(evt);
            }
        });

        btn_Actualizar_Materias.setText("Actualizar");
        btn_Actualizar_Materias.setEnabled(false);
        btn_Actualizar_Materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Actualizar_MateriasActionPerformed(evt);
            }
        });

        btn_EliminarMaterias.setText("Eliminar");
        btn_EliminarMaterias.setEnabled(false);
        btn_EliminarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarMateriasActionPerformed(evt);
            }
        });

        cbx_materias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_materiasItemStateChanged(evt);
            }
        });

        btn_Nuevo_Materia.setText("Nuevo");
        btn_Nuevo_Materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Nuevo_MateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_MateriaLayout = new javax.swing.GroupLayout(jpanel_Materia);
        jpanel_Materia.setLayout(jpanel_MateriaLayout);
        jpanel_MateriaLayout.setHorizontalGroup(
            jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_MateriaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jpanel_MateriaLayout.createSequentialGroup()
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_NombreMateria)
                            .addComponent(txt_Abreviatura_Materia)
                            .addComponent(cbx_Cod_Facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_CicloMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_UV, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkb_estado_materia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_MateriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_MateriaLayout.createSequentialGroup()
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanel_MateriaLayout.createSequentialGroup()
                                .addComponent(btn_Nuevo_Materia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_GuardarMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Actualizar_Materias)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_MateriaLayout.createSequentialGroup()
                        .addComponent(cbx_materias, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_EliminarMaterias)
                        .addGap(142, 142, 142))))
        );
        jpanel_MateriaLayout.setVerticalGroup(
            jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_MateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EliminarMaterias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_MateriaLayout.createSequentialGroup()
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_Cod_Facultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_NombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Abreviatura_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jpanel_MateriaLayout.createSequentialGroup()
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_UV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_CicloMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(chkb_estado_materia))))
                .addGap(29, 29, 29)
                .addGroup(jpanel_MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_GuardarMateria)
                    .addComponent(btn_Actualizar_Materias)
                    .addComponent(btn_Nuevo_Materia))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanel_Materia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanel_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UVActionPerformed

    private void txt_UVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UVKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_UVKeyTyped

    private void txt_CicloMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CicloMateriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_CicloMateriaKeyTyped

    private void btn_GuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarMateriaActionPerformed
        Materias materia = new Materias();
        Facultades facultad = (Facultades) cbx_Cod_Facultad.getSelectedItem();
        materia.setAbrev_Materia(this.txt_Abreviatura_Materia.getText());
        materia.setCiclo_Materia(this.txt_CicloMateria.getText());
        materia.setEstado_Materia(this.chkb_estado_materia.isSelected());
        materia.setNombre_Materia(this.txt_NombreMateria.getText());
        materia.setUV_Materia(Integer.valueOf(this.txt_UV.getText()));
        materia.setCod_Facultad(facultad.getCod_Facultad());

        Integer id = materia.guardar(con); //guarda el registro y retorna el id generado

        if (id != null) {
            materia.setCod_Materia(id.intValue());
            cbx_materias.addItem(materia);
            this.btn_Nuevo_MateriaActionPerformed(null);
            JOptionPane.showMessageDialog(null, "El Registro se Guardo con Exito");
        } else {
            JOptionPane.showMessageDialog(null, "Error , Fallo al Guardar el Registro");
        }
    }//GEN-LAST:event_btn_GuardarMateriaActionPerformed

    private void btn_Actualizar_MateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Actualizar_MateriasActionPerformed
        Materias materia = (Materias) cbx_materias.getSelectedItem();
        Facultades facultad = (Facultades) cbx_Cod_Facultad.getSelectedItem();
        if (materia != null && materia.getNombre_Materia() != null) {
            materia.setAbrev_Materia(this.txt_Abreviatura_Materia.getText());
            materia.setCiclo_Materia(this.txt_CicloMateria.getText());
            materia.setEstado_Materia(this.chkb_estado_materia.isSelected());
            materia.setNombre_Materia(this.txt_NombreMateria.getText());
            materia.setUV_Materia(Integer.valueOf(this.txt_UV.getText()));
            materia.setCod_Facultad(facultad.getCod_Facultad());
            if (materia.actualizar(con)) {
                JOptionPane.showMessageDialog(null, "El Registro se actualizo con Exito");
                this.btn_Nuevo_MateriaActionPerformed(null);
                obtenerMaterias();
            } else {
                JOptionPane.showMessageDialog(null, "Error , Fallo al actualizar el Registro");
            }
        }
    }//GEN-LAST:event_btn_Actualizar_MateriasActionPerformed

    private void btn_EliminarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarMateriasActionPerformed
        Materias materia = (Materias) cbx_materias.getSelectedItem();
        if (materia != null && materia.getNombre_Materia() != null) {
            int result = JOptionPane.showConfirmDialog(this, "Desea Eliminar el Registro", "Salir", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_NO_OPTION) {
                if (materia.eliminar(con)) {
                    JOptionPane.showMessageDialog(null, "El Registro se Elimino con Exito");
                    this.btn_Nuevo_MateriaActionPerformed(null);
                    obtenerMaterias();
                } else {
                    JOptionPane.showMessageDialog(null, "Error , Fallo al Eliminar el Registro");
                }
            }
        }
    }//GEN-LAST:event_btn_EliminarMateriasActionPerformed

    private void cbx_materiasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_materiasItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Materias item = (Materias) evt.getItem();
            if (item.getNombre_Materia() != null) {
                controlesMaterias(false);
                this.cbx_Cod_Facultad.setSelectedItem(new Facultades(item.getCod_Facultad()));
                this.txt_Abreviatura_Materia.setText(item.getAbrev_Materia());
                this.txt_CicloMateria.setText(item.getCiclo_Materia());
                this.chkb_estado_materia.setSelected(item.isEstado_Materia());
                this.txt_NombreMateria.setText(item.getNombre_Materia());
                this.txt_UV.setText(String.valueOf(item.getUV_Materia()));
            }
            else
            controlesMaterias(true);
        }
    }//GEN-LAST:event_cbx_materiasItemStateChanged

    private void btn_Nuevo_MateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Nuevo_MateriaActionPerformed
        this.cbx_Cod_Facultad.setSelectedIndex(0);
        this.txt_Abreviatura_Materia.setText("");
        this.txt_CicloMateria.setText("");
        this.chkb_estado_materia.setSelected(false);
        this.txt_NombreMateria.setText("");
        this.txt_UV.setText("");
        this.cbx_materias.setSelectedIndex(0);
    }//GEN-LAST:event_btn_Nuevo_MateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar_Materias;
    private javax.swing.JButton btn_EliminarMaterias;
    private javax.swing.JButton btn_GuardarMateria;
    private javax.swing.JButton btn_Nuevo_Materia;
    private javax.swing.JComboBox cbx_Cod_Facultad;
    private javax.swing.JComboBox cbx_materias;
    private javax.swing.JCheckBox chkb_estado_materia;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jpanel_Materia;
    private javax.swing.JTextField txt_Abreviatura_Materia;
    private javax.swing.JTextField txt_CicloMateria;
    private javax.swing.JTextField txt_NombreMateria;
    private javax.swing.JTextField txt_UV;
    // End of variables declaration//GEN-END:variables
}
