/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

/**
 *
 * @author Nataly
 */
public class Recursos_solicitados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Recursos_soli
     */
    public Recursos_solicitados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Titulo_RecSolicitado = new javax.swing.JLabel();
        cbx_UsuarioR = new javax.swing.JComboBox();
        cbx_MateriaR = new javax.swing.JComboBox();
        cbx_SeccionR = new javax.swing.JComboBox();
        cbx_AulaR = new javax.swing.JComboBox();
        lbl_UsuarioP = new javax.swing.JLabel();
        lbl_MateriaP = new javax.swing.JLabel();
        lbl_SeccionP = new javax.swing.JLabel();
        lbl_AulaP = new javax.swing.JLabel();
        lbl_AulaP1 = new javax.swing.JLabel();
        lbl_DetalleRecP = new javax.swing.JLabel();
        lbl_AulaP5 = new javax.swing.JLabel();
        lbl_AulaP6 = new javax.swing.JLabel();
        lbl_RecSolP = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_GenerarReporteR = new javax.swing.JButton();
        btn_MenuPrincipalR = new javax.swing.JButton();
        btn_CancelarR = new javax.swing.JButton();
        btn_SalirR = new javax.swing.JButton();
        lbl_MateriaP1 = new javax.swing.JLabel();
        cbx_RecursoR = new javax.swing.JComboBox();
        dpk_FechaRec = new org.jdesktop.swingx.JXDatePicker();
        txt_CantRecR = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_RecursosSolR = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lbl_Titulo_RecSolicitado.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Titulo_RecSolicitado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo_RecSolicitado.setText("RECURSOS SOLICITADOS");

        cbx_UsuarioR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbx_MateriaR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_MateriaR.setEnabled(false);

        cbx_SeccionR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_SeccionR.setEnabled(false);

        cbx_AulaR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_AulaR.setEnabled(false);

        lbl_UsuarioP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_UsuarioP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_UsuarioP.setText("Usuario:");

        lbl_MateriaP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_MateriaP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_MateriaP.setText("Materia:");

        lbl_SeccionP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_SeccionP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SeccionP.setText("Sección:");

        lbl_AulaP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP.setText("Aula:");

        lbl_AulaP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP1.setText("Fecha:");

        lbl_DetalleRecP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_DetalleRecP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DetalleRecP.setText("Detalle:");

        lbl_AulaP5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP5.setForeground(new java.awt.Color(204, 204, 204));
        lbl_AulaP5.setText("* Complete la siguiente información requerida para generar el reporte de Reserva de Parcial:");

        lbl_AulaP6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP6.setForeground(new java.awt.Color(204, 204, 204));
        lbl_AulaP6.setText("* Elíga su usuario para auto-completar el registro que corresponda, puede cambiar las opciones si lo desea:");

        lbl_RecSolP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_RecSolP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_RecSolP.setText("Cantidad de recurso solicitado:");

        btn_GenerarReporteR.setText("Generar Reporte");

        btn_MenuPrincipalR.setText("Menú Principal");

        btn_CancelarR.setText("Cancelar");

        btn_SalirR.setText("Salir");

        lbl_MateriaP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_MateriaP1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_MateriaP1.setText("Tipo de Recurso:");

        cbx_RecursoR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_RecursoR.setEnabled(false);

        tbl_RecursosSolR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_RecursosSolR);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_MateriaP1)
                        .addGap(41, 41, 41)
                        .addComponent(cbx_RecursoR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_AulaP6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MateriaP)
                            .addComponent(lbl_UsuarioP))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbx_UsuarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_MateriaR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SeccionP)
                            .addComponent(lbl_AulaP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_AulaR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_SeccionR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_AulaP5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_AulaP1)
                                                .addGap(18, 18, 18)
                                                .addComponent(dpk_FechaRec, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_DetalleRecP)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField1)))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_GenerarReporteR)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_RecSolP)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_CantRecR, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(lbl_Titulo_RecSolicitado)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_MenuPrincipalR)
                        .addGap(18, 18, 18)
                        .addComponent(btn_CancelarR)
                        .addGap(18, 18, 18)
                        .addComponent(btn_SalirR)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Titulo_RecSolicitado)
                .addGap(18, 18, 18)
                .addComponent(lbl_AulaP6)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_SeccionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_UsuarioP)
                    .addComponent(lbl_SeccionP)
                    .addComponent(cbx_UsuarioR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_MateriaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_AulaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MateriaP)
                    .addComponent(lbl_AulaP))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MateriaP1)
                    .addComponent(cbx_RecursoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_AulaP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AulaP1)
                    .addComponent(lbl_RecSolP)
                    .addComponent(dpk_FechaRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CantRecR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DetalleRecP)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_GenerarReporteR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_MenuPrincipalR)
                    .addComponent(btn_CancelarR)
                    .addComponent(btn_SalirR))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancelarR;
    private javax.swing.JButton btn_GenerarReporteR;
    private javax.swing.JButton btn_MenuPrincipalR;
    private javax.swing.JButton btn_SalirR;
    private javax.swing.JComboBox cbx_AulaR;
    private javax.swing.JComboBox cbx_MateriaR;
    private javax.swing.JComboBox cbx_RecursoR;
    private javax.swing.JComboBox cbx_SeccionR;
    private javax.swing.JComboBox cbx_UsuarioR;
    private org.jdesktop.swingx.JXDatePicker dpk_FechaRec;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_AulaP;
    private javax.swing.JLabel lbl_AulaP1;
    private javax.swing.JLabel lbl_AulaP5;
    private javax.swing.JLabel lbl_AulaP6;
    private javax.swing.JLabel lbl_DetalleRecP;
    private javax.swing.JLabel lbl_MateriaP;
    private javax.swing.JLabel lbl_MateriaP1;
    private javax.swing.JLabel lbl_RecSolP;
    private javax.swing.JLabel lbl_SeccionP;
    private javax.swing.JLabel lbl_Titulo_RecSolicitado;
    private javax.swing.JLabel lbl_UsuarioP;
    private javax.swing.JTable tbl_RecursosSolR;
    private javax.swing.JTextField txt_CantRecR;
    // End of variables declaration//GEN-END:variables
}
