/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Util;
import Clases.Conexion;
import Clases.tablas.Personas;
import Clases.tablas.ParcialReservas;
import Clases.tablas.Usuarios;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nataly
 */
public class Reserva_Parcial extends javax.swing.JInternalFrame {

    private Conexion con;
    private Usuarios usuario;

    /**
     * Creates new form Reserva_Parc
     */
    public Reserva_Parcial(Usuarios usuario) throws SQLException {
        initComponents();
        con = new Conexion();
        this.usuario = usuario;
        txt_usuario.setText(this.usuario.getPersona().nombreCompleto());
        
        for (Object o : Clases.tablas.MateriasD.getMaterias(con)){
            cbx_MateriaP.addItem(o);
        }
        
        for (Object o : Clases.tablas.Aulas.getAulas(con)){
            cbx_AulaP.addItem(o);
        }
        
        for (Object o : Clases.tablas.Secciones.getSecciones(con)){
            cbx_SeccionP.addItem(o);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Titulo_ResParcial = new javax.swing.JLabel();
        cbx_MateriaP = new javax.swing.JComboBox();
        cbx_SeccionP = new javax.swing.JComboBox();
        cbx_AulaP = new javax.swing.JComboBox();
        lbl_UsuarioP = new javax.swing.JLabel();
        lbl_MateriaP = new javax.swing.JLabel();
        lbl_SeccionP = new javax.swing.JLabel();
        lbl_AulaP = new javax.swing.JLabel();
        lbl_AulaP1 = new javax.swing.JLabel();
        lbl_AulaP2 = new javax.swing.JLabel();
        lbl_AulaP5 = new javax.swing.JLabel();
        lbl_AulaP6 = new javax.swing.JLabel();
        cbx_HorariolP = new javax.swing.JComboBox();
        rbtn_SiAulaP = new javax.swing.JRadioButton();
        rbtn_NoVigilanteP = new javax.swing.JRadioButton();
        lbl_AulaP7 = new javax.swing.JLabel();
        rbtn_SiVigilanteP = new javax.swing.JRadioButton();
        rbtn_NoAulaP = new javax.swing.JRadioButton();
        lbl_AulaP3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_AulaP8 = new javax.swing.JLabel();
        rbtn_SiInstP = new javax.swing.JRadioButton();
        rbtn_NoInstP = new javax.swing.JRadioButton();
        btn_GenerarReporteP = new javax.swing.JButton();
        btn_MenuPrincipalP = new javax.swing.JButton();
        btn_CancelarP = new javax.swing.JButton();
        btn_SalirP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ReservParcial = new javax.swing.JTable();
        cbx_HorariolP1 = new javax.swing.JComboBox();
        cbx_diaParcial = new javax.swing.JComboBox();
        txt_usuario = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lbl_Titulo_ResParcial.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_Titulo_ResParcial.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo_ResParcial.setText("RESERVA DE PARCIALES");

        lbl_UsuarioP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_UsuarioP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_UsuarioP.setText("Usuario:");

        lbl_MateriaP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_MateriaP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_MateriaP.setText("Materia:");

        lbl_SeccionP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_SeccionP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SeccionP.setText("Sección:");

        lbl_AulaP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP.setText("Aula:");

        lbl_AulaP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP1.setText("Día del Parcial:");

        lbl_AulaP2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP2.setText("Horario:");

        lbl_AulaP5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP5.setForeground(new java.awt.Color(204, 204, 204));
        lbl_AulaP5.setText("* Complete la siguiente información requerida para generar el reporte de Reserva de Parcial:");

        lbl_AulaP6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP6.setForeground(new java.awt.Color(204, 204, 204));
        lbl_AulaP6.setText("* Elíga su usuario para auto-completar el registro que corresponda, puede cambiar las opciones si lo desea:");

        cbx_HorariolP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6:30-7:20", "7:20-8:10", "8:15-9:05", "9:05-9:55", "10:00-10:50", "10:50-11:40", "11:40-12:30", "13:00-13:50", "13:50-14:40", "14:40-15:30", "15:30-16:20", "16:20-17:10", "17:20-18:10", "18:10-19:00", "19:00-19:50", "19:50-20:40", "20:40-21:30" }));

        rbtn_SiAulaP.setText("Si");

        rbtn_NoVigilanteP.setText("No");

        lbl_AulaP7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP7.setText("¿Vigilancia?");

        rbtn_SiVigilanteP.setText("Si");

        rbtn_NoAulaP.setText("No");

        lbl_AulaP3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP3.setText("¿Aula Adicional?");

        lbl_AulaP8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_AulaP8.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AulaP8.setText("¿Instructor?");

        rbtn_SiInstP.setText("Si");

        rbtn_NoInstP.setText("No");

        btn_GenerarReporteP.setText("Generar Reporte");
        btn_GenerarReporteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerarReportePActionPerformed(evt);
            }
        });

        btn_MenuPrincipalP.setText("Menú Principal");

        btn_CancelarP.setText("Cancelar");

        btn_SalirP.setText("Salir");

        tbl_ReservParcial.setAutoCreateRowSorter(true);
        tbl_ReservParcial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Docente", "Dia", "Hora", "Aula Adicional"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ReservParcial.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tbl_ReservParcial);

        cbx_HorariolP1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6:30-7:20", "7:20-8:10", "8:15-9:05", "9:05-9:55", "10:00-10:50", "10:50-11:40", "11:40-12:30", "13:00-13:50", "13:50-14:40", "14:40-15:30", "15:30-16:20", "16:20-17:10", "17:20-18:10", "18:10-19:00", "19:00-19:50", "19:50-20:40", "20:40-21:30" }));
        cbx_HorariolP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_HorariolP1ActionPerformed(evt);
            }
        });

        cbx_diaParcial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" }));

        txt_usuario.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_AulaP6)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MateriaP)
                            .addComponent(lbl_UsuarioP))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbx_MateriaP, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_usuario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SeccionP)
                            .addComponent(lbl_AulaP))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbx_SeccionP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbx_AulaP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_AulaP5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_AulaP2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx_HorariolP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbx_HorariolP1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_AulaP1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbx_diaParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_AulaP3)
                                            .addComponent(lbl_AulaP7))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_AulaP8)
                                        .addGap(41, 41, 41)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_SiAulaP)
                                    .addComponent(rbtn_SiVigilanteP)
                                    .addComponent(rbtn_SiInstP))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_NoInstP)
                                    .addComponent(rbtn_NoVigilanteP)
                                    .addComponent(rbtn_NoAulaP))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(btn_GenerarReporteP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Titulo_ResParcial)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_MenuPrincipalP)
                        .addGap(18, 18, 18)
                        .addComponent(btn_CancelarP)
                        .addGap(18, 18, 18)
                        .addComponent(btn_SalirP)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Titulo_ResParcial)
                .addGap(18, 18, 18)
                .addComponent(lbl_AulaP6)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_SeccionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_UsuarioP)
                    .addComponent(lbl_SeccionP)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_MateriaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_AulaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MateriaP)
                    .addComponent(lbl_AulaP))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_AulaP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AulaP1)
                    .addComponent(rbtn_SiAulaP)
                    .addComponent(rbtn_NoAulaP)
                    .addComponent(lbl_AulaP3)
                    .addComponent(cbx_diaParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AulaP2)
                    .addComponent(cbx_HorariolP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_AulaP7)
                    .addComponent(rbtn_SiVigilanteP)
                    .addComponent(rbtn_NoVigilanteP)
                    .addComponent(cbx_HorariolP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AulaP8)
                    .addComponent(rbtn_SiInstP)
                    .addComponent(rbtn_NoInstP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_GenerarReporteP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_MenuPrincipalP)
                    .addComponent(btn_CancelarP)
                    .addComponent(btn_SalirP))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GenerarReportePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerarReportePActionPerformed

        DefaultTableModel model = (DefaultTableModel) tbl_ReservParcial.getModel();
        model.addRow(new Object[]{usuario.getNombre_Usuario(), cbx_diaParcial.getSelectedItem(), cbx_HorariolP.getSelectedItem() + " " + cbx_HorariolP1.getSelectedItem(), true});

    }//GEN-LAST:event_btn_GenerarReportePActionPerformed

    private void cbx_HorariolP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_HorariolP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_HorariolP1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancelarP;
    private javax.swing.JButton btn_GenerarReporteP;
    private javax.swing.JButton btn_MenuPrincipalP;
    private javax.swing.JButton btn_SalirP;
    private javax.swing.JComboBox cbx_AulaP;
    private javax.swing.JComboBox cbx_HorariolP;
    private javax.swing.JComboBox cbx_HorariolP1;
    private javax.swing.JComboBox cbx_MateriaP;
    private javax.swing.JComboBox cbx_SeccionP;
    private javax.swing.JComboBox cbx_diaParcial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_AulaP;
    private javax.swing.JLabel lbl_AulaP1;
    private javax.swing.JLabel lbl_AulaP2;
    private javax.swing.JLabel lbl_AulaP3;
    private javax.swing.JLabel lbl_AulaP5;
    private javax.swing.JLabel lbl_AulaP6;
    private javax.swing.JLabel lbl_AulaP7;
    private javax.swing.JLabel lbl_AulaP8;
    private javax.swing.JLabel lbl_MateriaP;
    private javax.swing.JLabel lbl_SeccionP;
    private javax.swing.JLabel lbl_Titulo_ResParcial;
    private javax.swing.JLabel lbl_UsuarioP;
    private javax.swing.JRadioButton rbtn_NoAulaP;
    private javax.swing.JRadioButton rbtn_NoInstP;
    private javax.swing.JRadioButton rbtn_NoVigilanteP;
    private javax.swing.JRadioButton rbtn_SiAulaP;
    private javax.swing.JRadioButton rbtn_SiInstP;
    private javax.swing.JRadioButton rbtn_SiVigilanteP;
    private javax.swing.JTable tbl_ReservParcial;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
